Made some groovy POM changes to prevent the An API incompatibility was encountered while executing org.codehaus.mojo.groovy:groovy-maven-plugin:1.0-beta-3:testCompile: java.lang.NoSuchMethodError: org.codehaus.plexus.PlexusContainer.hasChildContainer(Ljava/lang/String;)Z error per http://buildingaircastles.blogspot.com/2011/11/getting-groovy-test-cases-to-run-with.html?showComment=1347309021222#c1576977392369149670